### ISSUE TITLE
Export stitch

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#10]
- [x] stitch video: 

- [x] change output times (dont want to do that because might use some parts of full video)

- [x] export stitch

**Comment by CIEspost** [comment]
@ApheleleM I have stitched this and am talking to @zacck 's friend Josh in Joburg in 2 days 
@zacck we need to make the appointment with josh please let me know about this?

**Comment by zacck-zz** [comment]
Will talk to Josh today to ask him when we can meet

**Comment by CIEspost** [comment]
@ApheleleM i have finished this, please see here the raw stitched video this is the clip we will be editing)
https://youtu.be/nUruwpVkW2c
