### ISSUE TITLE
edit video 

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#14]
have met josh and know that now I need to send him the edit first so that he knows what exactly needs narration.

- [x] edit ep 1 

- [x] uplaod and send to josh to start with narration

**Comment by CIEspost** [comment]
@ApheleleM I have made a rough edit of the video (see here https://youtu.be/LTfoOAyyfuw ) and would love some feedback from you please? (As you will see above, I will be sending this to Josh and he will add the narration from here on)
 
Some things I need to polish on the edit 

- [ ] polish masks in beginning where squirrel runs around tree 

- [ ] polish jumpcuts (there are 3 jump cuts in total, @ApheleleM please let me know what you think of these?)

- [ ] fix sound (the rustle of the leaves don't sync with the imageand also the plastic from the paper that the squirrel chews  needs to be added and polished)

**Comment by CIEspost** [comment]
@ApheleleM i have a feeling we should start the video at second 00:13 rather?

**Comment by ApheleleM** [comment]
Yes we could that cut the Dove out, I like the Video. it will be great after the narration

**Comment by ApheleleM** [comment]
dove

**Comment by CIEspost** [comment]
cool! @ApheleleM how does this look https://youtu.be/kxYRA_jg14U ?

**Comment by CIEspost** [comment]
now i just need the sound from Josh and then I need to grade it

**Comment by ApheleleM** [comment]
I think its on Point Dear, this is short and interesting '

**Comment by CIEspost** [comment]
@ApheleleM great to hear thanks. Now lets see what Josh comes up with

**Comment by ApheleleM** [comment]
did you at least Give him a Brief of what we looking for, or what we expected

**Comment by CIEspost** [comment]
Yes we did @ApheleleM , just spoke to him, he is gonna sort something out asap!

**Comment by ApheleleM** [comment]
great to hear

**Comment by CIEspost** [comment]
carla must add masks to jumpcuts
