### ISSUE TITLE
Zacck add basic labels to CIEproductions repo

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#21]
label system might not work right now, delete some exxtras @carla

**Comment by zacck-zz** [comment]
@CIEspost  aren't we reviewing labels on the 2nd of August with Aphelele ?

**Comment by CIEspost** [comment]
@zacck yes we are reviwing labels with Aphelele, but I still think we can start adding the basic labels you created for hapihour to the CIEproductions repo please, then I will go through these with Aphelele and we will delete the labels that dont work for us etc

**Comment by CIEspost** [comment]
@zacck i changed this issues name to make more sense, the other issue is for me and Aphelele to review the labels

**Comment by zacck-zz** [comment]
@CIEspost  ok will find time for this on my sprint action items
