### ISSUE TITLE
shoot sound for ep 1

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#23]
@ApheleleM we are going to shoot at the gardens now

**Comment by ApheleleM** [comment]
cool lets do that

**Comment by CIEspost** [comment]
- [ ] make sure front of recorder shows towards bin 

- [ ]  shoot 5mins of sound  

- [ ] shoot 5mins blank (no walking)  

- [ ] shoot seperate clip renacting walking 

- [ ] renact squirrel plastic bag sounds, 30cm from mic, behind 

- [ ] make sure we get 2 people walking from cbd to gardens side

![image](https://user-images.githubusercontent.com/19358273/28240432-16fcf4aa-6982-11e7-8eb7-c36acfcdda57.png)
