### ISSUE TITLE
evaluate sprint

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#29]
See here link to CIEproductions_Zenhub_bible (production planning guide) https://docs.google.com/spreadsheets/d/1AYHSk2Q_ae3fjRXRKROart8m0dWsk2WLvXFYkWN32LY/edit#gid=0

**Comment by CIEspost** [comment]
NOTE: | Keep going back and evalutaing board columns
-- | --
  | *Once sprint ends assignees can report problems and discuss efficiancy (look at these questions when in need of clarity):
  | Does this structure contain only what we need, and nothing more? Could my boss look at this and understand everything she needs to about the project?
  | Is every important stakeholder represented? Can someone in design, marketing, or QA look at this board and know exactly where his or her help is needed?
  | Are we missing any repeating stages? Think about how your team builds products. It's all about keeping issues flowing across the board. If you have a QA department, for example, you might need a “Ready for QA” pipeline.
  | Is “Done” really done? And does my team know and understand our definition of Done? This often-missed step is a crucial part of any agile project.

**Comment by CIEspost** [comment]
See here link to CIEproductions_Zenhub_bible (production planning guide) https://docs.google.com/spreadsheets/d/1AYHSk2Q_ae3fjRXRKROart8m0dWsk2WLvXFYkWN32LY/edit#gid=0

**Comment by CIEspost** [comment]
Read more about sprints

- [ ] https://thepathforward.io/how-to-run-a-sprint-for-a-small-startup-product-team/

 

- [ ] https://www.targetprocess.com/guide/entity-types/iterations-sprints/

**Comment by CIEspost** [comment]
@zacck we can look at it jsut to see, maybe there are some tstuff to look at,l perhaps then lets look at it to see what we can do better for the next sprint? please list what we need to do to use this properly?

**Comment by zacck-zz** [comment]
@CIEspost  We can surely look at it.

**Comment by CIEspost** [comment]
@zacck lets do this quick

**Comment by zacck-zz** [comment]
Currently the milestone records say we finished 70% of the work with 8 issues being close out of 11 
I dont think this is right as we did way more work and closed way more issues. We should ideally label all the issues we are going to tackle with the current milestone now and then we can begin work. I think we lost same evalution data here but we can definitely do 10X better if we do the next one together

**Comment by CIEspost** [comment]
@zacck ok cool so lets add the milestone and do that then now plz

**Comment by zacck-zz** [comment]
@CIEspost  to do this we need to align our aims for this sprint
