### ISSUE TITLE
Carla and Aphelele review labels for CIEproductions

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#36]
@ApheleleM i think the labels we made for this Zenhub board is a bit confusing, is that perhaps what is bothering you here?

@zacck can you maybe look at our labels list and help us create better ones? @zacck i was thinking we use the same ones as hapihour, but just add more departments in terms of the types you have in the hapihour labels list (e.g. marketing or bussiness.) your thoughts?

**Comment by zacck-zz** [comment]
@ApheleleM  @CIEspost  lets all set a date to discuss labels it takes a few minutes but I realize this things need everyone to be present when being chosen

**Comment by CIEspost** [comment]
@zacck cool me and @ApheleleM are meeting on the 2nd of August, so can we make sure we sort this out then if that date is fine with you too please?

**Comment by ApheleleM** [comment]
Yes we Could Meet, I dont Mind at all, after work sounds Great

**Comment by zacck-zz** [comment]
Good lets plan on that, Come prepared to discuss types of issues you can see and the types of situations those issues are it.

**Comment by CIEspost** [comment]
@ApheleleM we can talk about this in the meeting now

**Comment by CIEspost** [comment]
@ApheleleM please let us know if you managed to find that Board button ?

**Comment by CIEspost** [comment]
Also @ApheleleM please see here for the current labels we are using (just read through them please, I just want you to familiarize yourself with the full list of labels, as you can see we added some from when we last spoke about the labels) https://github.com/zacck/cieproductions/labels

Let me know when you have done this and then I can close the issue as done

**Comment by ApheleleM** [comment]
![1](https://user-images.githubusercontent.com/30198677/29065828-a61352a2-7c2d-11e7-8ff0-e1afbc5616aa.JPG)
@CIEspost  please see the attached screenshot of my Zanhub wall. So I Cannot find the "Board Button"

**Comment by zacck-zz** [comment]
@ApheleleM  please go to this link https://www.zenhub.com/ and press `Add Zenhub to Github`
Then sign in with your github
The come back to that page and refresh

**Comment by ApheleleM** [comment]
@CIEspost I am on Board thank you,

**Comment by CIEspost** [comment]
@ApheleleM Awesome glad to hear

**Comment by zacck-zz** [comment]
@ApheleleM  are you comfortable with the current labels is there any whose meaning is ambiguous? 
![image](https://user-images.githubusercontent.com/19358273/29108416-2119cd6c-7cdf-11e7-88df-c324739b3b85.png)

**Comment by ApheleleM** [comment]
@CIEspost Yes I am, Thank you

**Comment by CIEspost** [comment]
Cool then I will close the issue
