### ISSUE TITLE
pick up and pay S6 from WeFix shop

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#41]
- [x] mail papa insurance geld? 

- [x] mail wefix and confirm fix 

- [x] mail melite thank you 

- [x] budget how much needed to pay extra

**Comment by CIEspost** [comment]
- wait for mail from wefix (confirm fix)
- wait for money from insurance (tricom sending through)
- pay extra R350

**Comment by CIEspost** [comment]
@zacck We have R1730, we need to pay R2228 in total, this will be needed to be paid in 10 days aka the 9th of august

**Comment by CIEspost** [comment]
@zacck the phone is ready to be picked up. I told them I will come fetch it next week some time, so now we just need to make the cash and then we can go fetch it.

**Comment by CIEspost** [comment]
@zacck it seems we will ahve to use the 15th money to get this? we need to look at that budget again

**Comment by zacck-zz** [comment]
@CIEspost  we should make time for that either today or tomorrow please

**Comment by CIEspost** [comment]
@zacck , yes cool, lets discuss this meeting in the budget issue please, i asked you to make a time and date for that there

**Comment by zacck-zz** [comment]
@CIEspost  this issue has become something else can we open another or use another for the screen cover ?

**Comment by CIEspost** [comment]
@zacck this issue is done long ago
