### ISSUE TITLE
carla meet Aphelele

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#43]
I think we should meet this Saturday rather than Wednesday if possible

**Comment by CIEspost** [comment]
call Aphelele

**Comment by CIEspost** [comment]
We are meeting to discuss business, review sprint, Aphelele's questions about zenhub boards and also way forward for hapihour series, but carla needs to teach Aphelele editing for 360 video though.

**Comment by CIEspost** [comment]
First see what is in sprint

**Comment by CIEspost** [comment]
First see what is in sprint:

**Comment by CIEspost** [comment]
Discuss rates
&
Review labels

**Comment by CIEspost** [comment]
Also ask Aphelele about afrihost, maybe she can learn editing etc. at home with afrihost internet, then we can skype on weekends and do work via internet @zacck your thoughts? I was thinking my next sprint I will start working on CIEproductions bussiness plan so that I can start getting jobs for aphelele - even if it is on upwork?

**Comment by CIEspost** [comment]
@carla make meeting with Aphelele quick one, but first make sure about what to make meeting

**Comment by zacck-zz** [comment]
@CIEspost  I think the afrihost internet is something we need to keep either for us, Josh or Aphelele. 
let's  discuss on what you want to cover in the meeting with her. Sure  for the next sprint we can tackle the business plan and how that can shape CIE productions

**Comment by CIEspost** [comment]
@zacck  i am talking to aphelele about editing short videos for little kidogo, and giving her afrihost for that. I am also talking to her about the zenhub and how thats going for her and what she would want to change and then i am gonna ask her to send through her 2d video rates for editing web content

**Comment by CIEspost** [comment]
@zacck we have met and decided on editing short videos for little kidogo, carla must send the brief through to @ApheleleM 
Also Carla and Aphelele have decided to meet on Saturdays to teach Aphelele 360 video editing (our first meeting will be this coming saturday the 12th, i am making a new issue for that now)
@ApheleleM we have also agreed to meet today 8 August at 5:15 to fetch the broken laptop

**Comment by ApheleleM** [comment]
@CIEspost Yes we meeting Today, for the Laptop and I would also Like to discuss the shares of the business( CIE productions), you Once offered me. "

**Comment by CIEspost** [comment]
@ApheleleM ok cool we can do that @zacck we need to determine how much the business is worth when you have time please

**Comment by zacck-zz** [comment]
@CIEspost  can we schedule to do this later today? Or this week ?

**Comment by CIEspost** [comment]
@zacck yes please i am making an issue for that

**Comment by CIEspost** [comment]
@ApheleleM I will speak to you next week about the shares as Zacck will be explaining to me how it works later this week only.

**Comment by zacck-zz** [comment]
@CIEspost  then we can close this issue and advance with the one that are borne of it ?

**Comment by CIEspost** [comment]
Yes the meeting is done.

SO to wrap this up, here is a summary of the meeting:

From the meeting @ApheleleM and @carla discussed the shares and decided it is a good idea, now @zacck needs to explain to @carla about the shares
@ApheleleM is there anything im forgetting ?

**Comment by zacck-zz** [comment]
@CIEspost  closing this then  we shall deal with the #55  shares discussion on that issue

**Comment by ApheleleM** [comment]
@CIEspost  No,  not that I can remember
