### ISSUE TITLE
Do interview for Daily Vlog possible CLient

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#48]
@ApheleleM please see the details of the job here

I NEED A PROFESSIONAL VIDEO EDITOR TO EDIT DAILY VLOGS FOR YOUTUBE!!!
IM LOOKING FOR YOU!!!!!!!!!
Im seeking a highly motivated, extremely energetic, laser sharp focused, unstoppably committed, very creative Video Editor, to edit DAILY VLOG for Youtube!!
My Name is Claudius Vertesi, take a look at my Subscribers Count!!
What is my NEWEST Video ?
What are my TOP 5 Viral YouTube Videos ?
My Videos are extremely fast paced, very hyper tone, bounce off the wall energy filled & right in Your face engaging STORY TELLING VLOGS!!
FUN & CREATIVE, HYPER ENERGY, NO CHILL, SUPER JACKED, OUTRAGEOUS & ACTION PACKED ADVENTURES TO THE MAX!!!!!
LETS ROCK !!!!!!!!!https://www.upwork.com/ab/proposals/interview/393394147

**Comment by CIEspost** [comment]
@ApheleleM this is the questions he is asking on the application 

Are You UNSTOPPABLY Committed to Edit DAILY VLOGS ? Are You highly motivated, Creative & Focused ? Are You a communicative & open minded person ? Do You have fast & reliable Wifi ? Do You LOVE Video Editing ?

How many People have You done Video Editing for ? Are You OBSESSED with delivering Quality Content on a DAILY BASIS ? Are You excited to tell amazing stories with Videos ? Are You highly motivated to push Yourself ? Do You LOVE learning new things?

Do You LOVE developing New Skills ? Do You hate sloppy & unfinished work ? On a Scale from 1- 10 is 11 or even 12 an option for You ? Do You love dreaming Big & thinking outside the Box ? Are You OBSESSED with winning & BEING AWESOME ??

**Comment by CIEspost** [comment]
@ApheleleM this is his channel https://www.youtube.com/user/VERTESI1802

**Comment by CIEspost** [comment]
@ApheleleM we decided we will be meeting Monday 07 August after work, I will come pick you up at 6pm and drop you at the station again after if thats good?

**Comment by ApheleleM** [comment]
yes we are meeting today, please lets meet at 17:15 by the stairs

**Comment by CIEspost** [comment]
@ApheleleM I got this message yesterday:


Claudius Vertesi 5:32 AM EET, 12 Aug 2017
Dear Carla , I highly apologise for not answering for 4 Days!At the Moment Im traveling & I have unstoppable constant 24/7 meetings in New York.This Editing Trial is very meaningful for me, because I want to find my perfect match to potentially work together for a healthy long time!We have quit a few potential competitors who are seriously driven & on fire in this long Term Mission!I do not see this “Vlog Trial” as a quick opportunity to make some money for the Editor.I want to build a long term relationship with someone who I can fully trust, rely on EVERY DAY, who is unstoppably motivated & committed & literally thrilled & inspire to Edit these Vlogs long term!I have the feeling in my heart that One of You will be the right person who will succeed & who will get this Unbelievable Opportunity to join this Mission!!I will be back in the UK starting Tuesday & then I have super fast reliable Wifi, so that I can send this “Vlog Trial Package” to all the competitors at the same time, so that everyone has a fair chance & equal time to Finnish this “Trial Vlog”.Thank You very much for understanding! IM ON FIRE to find the right Person once I will send everyone the right package!If YOU are the right person & if YOU feel that there is a calling for You to attain this Opportunity & to join THIS MISSION,GO GET IT!!!I WILL RECOGNISE YOU!!! Claudius Vertesi
--

**Comment by CIEspost** [comment]
@carla reply to message on upwork

**Comment by zacck-zz** [comment]
@CIEspost  I don't like that you guys have to compete to get a job. I don't feel you should invest time in this

**Comment by CIEspost** [comment]
@zacck this guy got back to me and anyways have found anther editor, so no worries about this, but i hear you

**Comment by zacck-zz** [comment]
👍
