### ISSUE TITLE
Little Kidogo social media campaign August

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#51]
CIEproductions has a client called Little Kidogo and we are in charge of their social media marketing for now. 

The main products that we are marketing is vintage clothes

The main platforms we are marketing on is Facebook, Gumtree and Etsy

See the links here: 

Gumtree: https://www.gumtree.co.za/u-seller-listings/little-kidogo-market/v1u112288713p1

Facebook: https://www.facebook.com/littlekidogo/

Etsy:

**Comment by CIEspost** [comment]
@zacck more about Marketing your Vintage Business

The beauty of one-of-a-kind is the availability of content. With new items arriving constantly, COAL N TERRY uses Instagram to quickly get iPhone snaps in front of their loyal customers right away.

Azeezat and Dare have grown the account (and the business) without spending money on any formal advertising. They rely on shoutouts from celeb or influencer partners, and user-generated content in the form of customer photos.

**Comment by CIEspost** [comment]
"We actively ask customers to share their photos. As soon as they get their purchase confirmation there's also a note in there saying, ‘Hey, this is our Instagram. Make sure to tag us. We'll post you. We can't wait to see you.’ Things like that.”

**Comment by CIEspost** [comment]
Instagram is their number one driver of sales, and they use Snappic to superpower their Instagram and turn it into a shoppable gallery.

"Instagram for us is 70 percent a selling tool. When we post customer pictures, it gives other customers an idea of how they could style their clothes. They can also see that we are a reputable business and we've had real people buy from us. At the same time, we do a lot of behind the scenes to let people know what's coming next. It looks cool and pretty but really, it's a huge selling tool for us.” @zacck very interesting

**Comment by zacck-zz** [comment]
@CIEspost  also this should be written out as a blog post. Consider doing one called `The State of marketing vintage items in 2017'

**Comment by CIEspost** [comment]
@zacck awesome will do,made issue for it already

**Comment by zacck-zz** [comment]
👍  please when you have that written use the blog post to close this issue @CIEspost

**Comment by CIEspost** [comment]
@zacck here is the blog https://medium.com/@carlaespost/little-kidogo-market-the-state-of-social-media-marketing-for-vintage-clothes-in-2017-50ad80b4001b

**Comment by zacck-zz** [comment]
👍  can we close this issue now ?

**Comment by CIEspost** [comment]
yes
