### ISSUE TITLE
zacck explain shares to Carla

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#54]

**Comment by zacck-zz** [comment]
@CIEspost can we schedule this so it can go in the calendar ?

**Comment by CIEspost** [comment]
@zacck aaah yes please, I am happy whenever fits you? lets make it on calender yes please

**Comment by zacck-zz** [comment]
@CIEspost tonight as we make dinner

**Comment by CIEspost** [comment]
This is done thanks @zacck
