### ISSUE TITLE
meet aphelele saturday

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#56]
- we will be working on a photo shoot with my flatmate and her friend who will model
- we will discuss the little kidogo videos
- we will teach @ApheleleM hwo to edit 360 video

**Comment by CIEspost** [comment]
@ApheleleM you last mentioned you have a white backdrop, what is needed to put it up again? Do you think it will fit in my living room?

**Comment by CIEspost** [comment]
@ApheleleM please remember to bring the hardrive I gave you the other day as i want to add more videos to it

**Comment by CIEspost** [comment]
@ApheleleM we never got to do the following last saturday 
1) discuss the little kidogo videos
2) teach @ApheleleM how to edit 360 video

We will do this Saturday the 19th

**Comment by ApheleleM** [comment]
I still have the WHITE cLOTH, we might as well use it for the next shoot

**Comment by CIEspost** [comment]
@ApheleleM oh that would be great, what type of stands does the cloth need?

**Comment by ApheleleM** [comment]
I dont have the stands

**Comment by ApheleleM** [comment]
@CIEspost  what time are we meeting

**Comment by CIEspost** [comment]
@ApheleleM on Tuesday i mentioned in another issue as a reply to your comment that we were meeting wednesday #49  that we were not going to meet on Wednesday, I am so sorry I am only getting back to you now as things have been very busy. Let's make sure we dont have this miscommunication again by means of checking whether we have replies from each other confirming we have seen messages. Also I will not be commenting on this issue here anymore as it is closed, Lets continue discussion on the appropriate issues please
