### ISSUE TITLE
Meet Aphelele  Saturday the 26th of August

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#58]
@ApheleleM we never got to do the following last saturday 
1) discuss the little kidogo videos #49 
2) teach @ApheleleM how to edit 360 video #47 
3) photo shoot with Maria

We will do this Saturday the 19th

**Comment by zacck-zz** [comment]
@CIEspost  what do  would you need me to do ?

**Comment by CIEspost** [comment]
@zacck please fix the laptop asap, make an issue for it and add it here

**Comment by CIEspost** [comment]
@ApheleleM you mentioned the white cloth in the other issue #56 
 that one was finished so I am restarting that conversation here 
SO yes it would be great to use the cloth please! What type of stands does the cloth need?

**Comment by zacck-zz** [comment]
@CIEspost  @ApheleleM haven't had time to go through the laptop will this today

**Comment by CIEspost** [comment]
@ApheleleM let's talk about this issue in_"tomorrows meeting" please

**Comment by CIEspost** [comment]
@ApheleleM we seem to have had some miscommunication last week. Can we try make arrangements to meet this Saturday the 26th of August please? I will not be able to meet this Wednesday the 23rd

**Comment by ApheleleM** [comment]
@CIEspost  I would like to Apologize for not pitching up this Saturday, I was Broke and did not even have airtime.

**Comment by zacck-zz** [comment]
@CIEspost @ApheleleM This should not have happened. All of us made a mistake here. 
Carla and I we apologize for not reaching out to you Aphelele we also had a busy weekend, However Aphelele I think the next time you find yourself in a circumstance such as this, Please email me or Carla or write an issue before you leave work. If we all communicated this would not have happened Aphelele don't get stuck alone speak to us and we should also not get stuck without you we should speak to you.

**Comment by ApheleleM** [comment]
@zacck  Lesson Learn, next time this will be Avoided.

**Comment by CIEspost** [comment]
@ApheleleM sorry man! How does things look for this weekend though?

**Comment by ApheleleM** [comment]
@CIEspost We can meet Wednesday and Saturday as well

**Comment by CIEspost** [comment]
@ApheleleM cool, I cannot meet Wednesday, but I can meet Saturday yes

**Comment by ApheleleM** [comment]
@CIEspost  Saturday it is then

**Comment by CIEspost** [comment]
@ApheleleM awesome!!! ok, Saturday 11am , im trying to confirm with Maria about a photo shoot, so will get back to you about the agende for saturday, but the date and time is set

**Comment by CIEspost** [comment]
@ApheleleM i want to do a little interview with you on Saturday, me and maria got the idea that we should do interviews with our models and put it with that video we took of you guys dancing, just want to give you a headsup so you know you will be in front of the camera. We will only be doing the interview (just me and you) and not a photo shoot

**Comment by ApheleleM** [comment]
@CIEspost  Okay then

**Comment by CIEspost** [comment]
Final Agenda for Saturday:

- [x] shoot interview with Aphelele 
- [ ] go through Squirrel video and finalize script for this https://github.com/zacck/cieproductions/issues/11

- [x] teach Aphelele how to edit 360 video

- [x] go through rushes and select 2d videos to use

- [ ] Edit final interview video featuring Aphelele

**Comment by CIEspost** [comment]
@ApheleleM we didnt get through everything, and I totally forgot about the squirrel video, can you please look at it asap and tell us what you think see the issue here #28

**Comment by CIEspost** [comment]
#[Creating issue: edit Aphelele interview video...]

**Comment by CIEspost** [comment]
#61 edit Aphelele interview video

**Comment by zacck-zz** [comment]
@CIEspost  This issue was completed without an estimate can we watch out for this, Also we need to introduce @ApheleleM  to the concept

**Comment by CIEspost** [comment]
@zacck cool will do, lets add our comments on estimates in that doucment of ours (the zenhub bible) we need to update it hey

**Comment by zacck-zz** [comment]
@CIEspost  niiice solution for that awesome will add the bit about estimates on it

**Comment by CIEspost** [comment]
@zacck cool so are you gonna add the info there plz?

**Comment by zacck-zz** [comment]
@CIEspost  yes I will 😄
