### ISSUE TITLE
zacck fix aphelele laptop

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#60]
@zacck please let's discuss this, before Saturday

**Comment by zacck-zz** [comment]
@ApheleleM  @CIEspost  I have looked at the laptop and I have some news for us.

- Yes there is a bit of smoke coming out of the charging unit though it seems to be from the insulation not electronics.
- The screen seems broken what happened?
- I think the best thing to do would be for @ApheleleM  to use the machine as much as she can at it is definitely on the way to retirement please lets utilize it while we have it as much as we can 

The best way forward is to plan a replacement machine for this

**Comment by CIEspost** [comment]
@zacck thanks, lets make an issue to find Aphelele a better machine #62
