### ISSUE TITLE
create production planning guide

### ISSUE THREAD

**Issue by CIEspost** [zacck/cieproductions#8]
see here for CIEproductions_Zenhub_bible (production planning guide) https://docs.google.com/spreadsheets/d/1AYHSk2Q_ae3fjRXRKROart8m0dWsk2WLvXFYkWN32LY/edit#gid=0

**Comment by CIEspost** [comment]
@ApheleleM please look at this document before you carry on with using this board, i completed the bible we started working on, please see here: https://docs.google.com/spreadsheets/d/1tRWn45AdoiVQIU7yGOUHrSw1eElssAqJT2158lLVtLg/edit?ts=596869a7#gid=0

please let me know if you have any questions 👍 :)

**Comment by CIEspost** [comment]
@ApheleleM did you manage to be able to see this document?

**Comment by ApheleleM** [comment]
yeah I saw it, Good luck Guys, I am very struggling with Zenhub

**Comment by CIEspost** [comment]
hey @ApheleleM thanks! OK please tell me what are you struggling with? 

Perhaps this video would help?

**Comment by CIEspost** [comment]
https://www.youtube.com/watch?v=TRu7vKCg920

**Comment by CIEspost** [comment]
Let me know if it helps and what questions you have specifically then ill try and help you as best I can?

**Comment by zacck-zz** [comment]
@ApheleleM  do you still need some guidance with zenhub ?

**Comment by CIEspost** [comment]
check in with Aphelele we are going to discuss this when we meet

**Comment by CIEspost** [comment]
@zacck can we please discuss these labels and write down what they mean https://github.com/zacck/hapihour/labels so that I can send the meanings of them to Aphelele and we can all understand and use them in the same context

**Comment by zacck-zz** [comment]
@CIEspost  yeah do you want to do that this morning ?

**Comment by CIEspost** [comment]
@zacck perhaps a bit later, I have to do the photos first

**Comment by zacck-zz** [comment]
Can we schedule this for 1pm then ?

**Comment by CIEspost** [comment]
ok cool

**Comment by zacck-zz** [comment]
👍

**Comment by CIEspost** [comment]
@zacck please let me know about the labels issue? Can we write down on this guide what they mean? Then we always have it written down for when someone new joins the team.
Also I think we need to write down what 'done' means for us on this guide as well.
I am thinking that for us 'done' means when we have reported back on an issue and made sure everyone agrees that its done... your thoughts?

**Comment by zacck-zz** [comment]
@CIEspost  good Idea we can work on an article explaining how we use labels can we start a medium or gdoc

**Comment by CIEspost** [comment]
@zacck please make an issue for yourself to write down the label meanings hey>?

**Comment by CIEspost** [comment]
i want to close this issue, as now its blocked by your issue

**Comment by zacck-zz** [comment]
#57
